require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DivisisController do

  # This should return the minimal set of attributes required to create a valid
  # Divisi. As you add validations to Divisi, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "keterangan" => "MyText" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DivisisController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all divises as @divises" do
      divisi = Divisi.create! valid_attributes
      get :index, {}, valid_session
      assigns(:divisis).should eq([divisi])
    end
  end

  describe "GET show" do
    it "assigns the requested divisi as @divisi" do
      divisi = Divisi.create! valid_attributes
      get :show, {:id => divisi.to_param}, valid_session
      assigns(:divisi).should eq(divisi)
    end
  end

  describe "GET new" do
    it "assigns a new divisi as @divisi" do
      get :new, {}, valid_session
      assigns(:divisi).should be_a_new(Divisi)
    end
  end

  describe "GET edit" do
    it "assigns the requested divisi as @divisi" do
      divisi = Divisi.create! valid_attributes
      get :edit, {:id => divisi.to_param}, valid_session
      assigns(:divisi).should eq(divisi)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Divisi" do
        expect {
          post :create, {:divisi => valid_attributes}, valid_session
        }.to change(Divisi, :count).by(1)
      end

      it "assigns a newly created divisi as @divisi" do
        post :create, {:divisi => valid_attributes}, valid_session
        assigns(:divisi).should be_a(Divisi)
        assigns(:divisi).should be_persisted
      end

      it "redirects to the created divisi" do
        post :create, {:divisi => valid_attributes}, valid_session
        response.should redirect_to(Divisi.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved divisi as @divisi" do
        # Trigger the behavior that occurs when invalid params are submitted
        Divisi.any_instance.stub(:save).and_return(false)
        post :create, {:divisi => { "keterangan" => "invalid value" }}, valid_session
        assigns(:divisi).should be_a_new(Divisi)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Divisi.any_instance.stub(:save).and_return(false)
        post :create, {:divisi => { "keterangan" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested divisi" do
        divisi = Divisi.create! valid_attributes
        # Assuming there are no other divisis in the database, this
        # specifies that the Divisi created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Divisi.any_instance.should_receive(:update_attributes).with({ "keterangan" => "MyText" })
        put :update, {:id => divisi.to_param, :divisi => { "keterangan" => "MyText" }}, valid_session
      end

      it "assigns the requested divisi as @divisi" do
        divisi = Divisi.create! valid_attributes
        put :update, {:id => divisi.to_param, :divisi => valid_attributes}, valid_session
        assigns(:divisi).should eq(divisi)
      end

      it "redirects to the divisi" do
        divisi = Divisi.create! valid_attributes
        put :update, {:id => divisi.to_param, :divisi => valid_attributes}, valid_session
        response.should redirect_to(divisi)
      end
    end

    describe "with invalid params" do
      it "assigns the divisi as @divisi" do
        divisi = Divisi.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Divisi.any_instance.stub(:save).and_return(false)
        put :update, {:id => divisi.to_param, :divisi => { "keterangan" => "invalid value" }}, valid_session
        assigns(:divisi).should eq(divisi)
      end

      it "re-renders the 'edit' template" do
        divisi = Divisi.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Divisi.any_instance.stub(:save).and_return(false)
        put :update, {:id => divisi.to_param, :divisi => { "keterangan" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested divisi" do
      divisi = Divisi.create! valid_attributes
      expect {
        delete :destroy, {:id => divisi.to_param}, valid_session
      }.to change(Divisi, :count).by(-1)
    end

    it "redirects to the divisis list" do
      divisi = Divisi.create! valid_attributes
      delete :destroy, {:id => divisi.to_param}, valid_session
      response.should redirect_to(divisis_url)
    end
  end

end
