require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GajisController do

  # This should return the minimal set of attributes required to create a valid
  # Gaji. As you add validations to Gaji, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "bonus" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GajisController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all gajis as @gajis" do
      gaji = Gaji.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gajis).should eq([gaji])
    end
  end

  describe "GET show" do
    it "assigns the requested gaji as @gaji" do
      gaji = Gaji.create! valid_attributes
      get :show, {:id => gaji.to_param}, valid_session
      assigns(:gaji).should eq(gaji)
    end
  end

  describe "GET new" do
    it "assigns a new gaji as @gaji" do
      get :new, {}, valid_session
      assigns(:gaji).should be_a_new(Gaji)
    end
  end

  describe "GET edit" do
    it "assigns the requested gaji as @gaji" do
      gaji = Gaji.create! valid_attributes
      get :edit, {:id => gaji.to_param}, valid_session
      assigns(:gaji).should eq(gaji)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gaji" do
        expect {
          post :create, {:gaji => valid_attributes}, valid_session
        }.to change(Gaji, :count).by(1)
      end

      it "assigns a newly created gaji as @gaji" do
        post :create, {:gaji => valid_attributes}, valid_session
        assigns(:gaji).should be_a(Gaji)
        assigns(:gaji).should be_persisted
      end

      it "redirects to the created gaji" do
        post :create, {:gaji => valid_attributes}, valid_session
        response.should redirect_to(Gaji.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gaji as @gaji" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gaji.any_instance.stub(:save).and_return(false)
        post :create, {:gaji => { "bonus" => "invalid value" }}, valid_session
        assigns(:gaji).should be_a_new(Gaji)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gaji.any_instance.stub(:save).and_return(false)
        post :create, {:gaji => { "bonus" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gaji" do
        gaji = Gaji.create! valid_attributes
        # Assuming there are no other gajis in the database, this
        # specifies that the Gaji created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gaji.any_instance.should_receive(:update_attributes).with({ "bonus" => "1" })
        put :update, {:id => gaji.to_param, :gaji => { "bonus" => "1" }}, valid_session
      end

      it "assigns the requested gaji as @gaji" do
        gaji = Gaji.create! valid_attributes
        put :update, {:id => gaji.to_param, :gaji => valid_attributes}, valid_session
        assigns(:gaji).should eq(gaji)
      end

      it "redirects to the gaji" do
        gaji = Gaji.create! valid_attributes
        put :update, {:id => gaji.to_param, :gaji => valid_attributes}, valid_session
        response.should redirect_to(gaji)
      end
    end

    describe "with invalid params" do
      it "assigns the gaji as @gaji" do
        gaji = Gaji.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gaji.any_instance.stub(:save).and_return(false)
        put :update, {:id => gaji.to_param, :gaji => { "bonus" => "invalid value" }}, valid_session
        assigns(:gaji).should eq(gaji)
      end

      it "re-renders the 'edit' template" do
        gaji = Gaji.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gaji.any_instance.stub(:save).and_return(false)
        put :update, {:id => gaji.to_param, :gaji => { "bonus" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gaji" do
      gaji = Gaji.create! valid_attributes
      expect {
        delete :destroy, {:id => gaji.to_param}, valid_session
      }.to change(Gaji, :count).by(-1)
    end

    it "redirects to the gajis list" do
      gaji = Gaji.create! valid_attributes
      delete :destroy, {:id => gaji.to_param}, valid_session
      response.should redirect_to(gajis_url)
    end
  end

end
