require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JabatansController do

  # This should return the minimal set of attributes required to create a valid
  # Jabatan. As you add validations to Jabatan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JabatansController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all jabatans as @jabatans" do
      jabatan = Jabatan.create! valid_attributes
      get :index, {}, valid_session
      assigns(:jabatans).should eq([jabatan])
    end
  end

  describe "GET show" do
    it "assigns the requested jabatan as @jabatan" do
      jabatan = Jabatan.create! valid_attributes
      get :show, {:id => jabatan.to_param}, valid_session
      assigns(:jabatan).should eq(jabatan)
    end
  end

  describe "GET new" do
    it "assigns a new jabatan as @jabatan" do
      get :new, {}, valid_session
      assigns(:jabatan).should be_a_new(Jabatan)
    end
  end

  describe "GET edit" do
    it "assigns the requested jabatan as @jabatan" do
      jabatan = Jabatan.create! valid_attributes
      get :edit, {:id => jabatan.to_param}, valid_session
      assigns(:jabatan).should eq(jabatan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Jabatan" do
        expect {
          post :create, {:jabatan => valid_attributes}, valid_session
        }.to change(Jabatan, :count).by(1)
      end

      it "assigns a newly created jabatan as @jabatan" do
        post :create, {:jabatan => valid_attributes}, valid_session
        assigns(:jabatan).should be_a(Jabatan)
        assigns(:jabatan).should be_persisted
      end

      it "redirects to the created jabatan" do
        post :create, {:jabatan => valid_attributes}, valid_session
        response.should redirect_to(Jabatan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jabatan as @jabatan" do
        # Trigger the behavior that occurs when invalid params are submitted
        Jabatan.any_instance.stub(:save).and_return(false)
        post :create, {:jabatan => {}}, valid_session
        assigns(:jabatan).should be_a_new(Jabatan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Jabatan.any_instance.stub(:save).and_return(false)
        post :create, {:jabatan => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jabatan" do
        jabatan = Jabatan.create! valid_attributes
        # Assuming there are no other jabatans in the database, this
        # specifies that the Jabatan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Jabatan.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => jabatan.to_param, :jabatan => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested jabatan as @jabatan" do
        jabatan = Jabatan.create! valid_attributes
        put :update, {:id => jabatan.to_param, :jabatan => valid_attributes}, valid_session
        assigns(:jabatan).should eq(jabatan)
      end

      it "redirects to the jabatan" do
        jabatan = Jabatan.create! valid_attributes
        put :update, {:id => jabatan.to_param, :jabatan => valid_attributes}, valid_session
        response.should redirect_to(jabatan)
      end
    end

    describe "with invalid params" do
      it "assigns the jabatan as @jabatan" do
        jabatan = Jabatan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Jabatan.any_instance.stub(:save).and_return(false)
        put :update, {:id => jabatan.to_param, :jabatan => {}}, valid_session
        assigns(:jabatan).should eq(jabatan)
      end

      it "re-renders the 'edit' template" do
        jabatan = Jabatan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Jabatan.any_instance.stub(:save).and_return(false)
        put :update, {:id => jabatan.to_param, :jabatan => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jabatan" do
      jabatan = Jabatan.create! valid_attributes
      expect {
        delete :destroy, {:id => jabatan.to_param}, valid_session
      }.to change(Jabatan, :count).by(-1)
    end

    it "redirects to the jabatans list" do
      jabatan = Jabatan.create! valid_attributes
      delete :destroy, {:id => jabatan.to_param}, valid_session
      response.should redirect_to(jabatans_url)
    end
  end

end
