require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KaryawansController do

  # This should return the minimal set of attributes required to create a valid
  # Karyawan. As you add validations to Karyawan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KaryawansController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all karyawans as @karyawans" do
      karyawan = Karyawan.create! valid_attributes
      get :index, {}, valid_session
      assigns(:karyawans).should eq([karyawan])
    end
  end

  describe "GET show" do
    it "assigns the requested karyawan as @karyawan" do
      karyawan = Karyawan.create! valid_attributes
      get :show, {:id => karyawan.to_param}, valid_session
      assigns(:karyawan).should eq(karyawan)
    end
  end

  describe "GET new" do
    it "assigns a new karyawan as @karyawan" do
      get :new, {}, valid_session
      assigns(:karyawan).should be_a_new(Karyawan)
    end
  end

  describe "GET edit" do
    it "assigns the requested karyawan as @karyawan" do
      karyawan = Karyawan.create! valid_attributes
      get :edit, {:id => karyawan.to_param}, valid_session
      assigns(:karyawan).should eq(karyawan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Karyawan" do
        expect {
          post :create, {:karyawan => valid_attributes}, valid_session
        }.to change(Karyawan, :count).by(1)
      end

      it "assigns a newly created karyawan as @karyawan" do
        post :create, {:karyawan => valid_attributes}, valid_session
        assigns(:karyawan).should be_a(Karyawan)
        assigns(:karyawan).should be_persisted
      end

      it "redirects to the created karyawan" do
        post :create, {:karyawan => valid_attributes}, valid_session
        response.should redirect_to(Karyawan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved karyawan as @karyawan" do
        # Trigger the behavior that occurs when invalid params are submitted
        Karyawan.any_instance.stub(:save).and_return(false)
        post :create, {:karyawan => {}}, valid_session
        assigns(:karyawan).should be_a_new(Karyawan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Karyawan.any_instance.stub(:save).and_return(false)
        post :create, {:karyawan => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested karyawan" do
        karyawan = Karyawan.create! valid_attributes
        # Assuming there are no other karyawans in the database, this
        # specifies that the Karyawan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Karyawan.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => karyawan.to_param, :karyawan => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested karyawan as @karyawan" do
        karyawan = Karyawan.create! valid_attributes
        put :update, {:id => karyawan.to_param, :karyawan => valid_attributes}, valid_session
        assigns(:karyawan).should eq(karyawan)
      end

      it "redirects to the karyawan" do
        karyawan = Karyawan.create! valid_attributes
        put :update, {:id => karyawan.to_param, :karyawan => valid_attributes}, valid_session
        response.should redirect_to(karyawan)
      end
    end

    describe "with invalid params" do
      it "assigns the karyawan as @karyawan" do
        karyawan = Karyawan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Karyawan.any_instance.stub(:save).and_return(false)
        put :update, {:id => karyawan.to_param, :karyawan => {}}, valid_session
        assigns(:karyawan).should eq(karyawan)
      end

      it "re-renders the 'edit' template" do
        karyawan = Karyawan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Karyawan.any_instance.stub(:save).and_return(false)
        put :update, {:id => karyawan.to_param, :karyawan => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested karyawan" do
      karyawan = Karyawan.create! valid_attributes
      expect {
        delete :destroy, {:id => karyawan.to_param}, valid_session
      }.to change(Karyawan, :count).by(-1)
    end

    it "redirects to the karyawans list" do
      karyawan = Karyawan.create! valid_attributes
      delete :destroy, {:id => karyawan.to_param}, valid_session
      response.should redirect_to(karyawans_url)
    end
  end

end
