require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PendidikansController do

  # This should return the minimal set of attributes required to create a valid
  # Pendidikan. As you add validations to Pendidikan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "from" => "2013-01-03" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PendidikansController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all pendidikans as @pendidikans" do
      pendidikan = Pendidikan.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pendidikans).should eq([pendidikan])
    end
  end

  describe "GET show" do
    it "assigns the requested pendidikan as @pendidikan" do
      pendidikan = Pendidikan.create! valid_attributes
      get :show, {:id => pendidikan.to_param}, valid_session
      assigns(:pendidikan).should eq(pendidikan)
    end
  end

  describe "GET new" do
    it "assigns a new pendidikan as @pendidikan" do
      get :new, {}, valid_session
      assigns(:pendidikan).should be_a_new(Pendidikan)
    end
  end

  describe "GET edit" do
    it "assigns the requested pendidikan as @pendidikan" do
      pendidikan = Pendidikan.create! valid_attributes
      get :edit, {:id => pendidikan.to_param}, valid_session
      assigns(:pendidikan).should eq(pendidikan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pendidikan" do
        expect {
          post :create, {:pendidikan => valid_attributes}, valid_session
        }.to change(Pendidikan, :count).by(1)
      end

      it "assigns a newly created pendidikan as @pendidikan" do
        post :create, {:pendidikan => valid_attributes}, valid_session
        assigns(:pendidikan).should be_a(Pendidikan)
        assigns(:pendidikan).should be_persisted
      end

      it "redirects to the created pendidikan" do
        post :create, {:pendidikan => valid_attributes}, valid_session
        response.should redirect_to(Pendidikan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pendidikan as @pendidikan" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pendidikan.any_instance.stub(:save).and_return(false)
        post :create, {:pendidikan => { "from" => "invalid value" }}, valid_session
        assigns(:pendidikan).should be_a_new(Pendidikan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pendidikan.any_instance.stub(:save).and_return(false)
        post :create, {:pendidikan => { "from" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pendidikan" do
        pendidikan = Pendidikan.create! valid_attributes
        # Assuming there are no other pendidikans in the database, this
        # specifies that the Pendidikan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pendidikan.any_instance.should_receive(:update_attributes).with({ "from" => "2013-01-03" })
        put :update, {:id => pendidikan.to_param, :pendidikan => { "from" => "2013-01-03" }}, valid_session
      end

      it "assigns the requested pendidikan as @pendidikan" do
        pendidikan = Pendidikan.create! valid_attributes
        put :update, {:id => pendidikan.to_param, :pendidikan => valid_attributes}, valid_session
        assigns(:pendidikan).should eq(pendidikan)
      end

      it "redirects to the pendidikan" do
        pendidikan = Pendidikan.create! valid_attributes
        put :update, {:id => pendidikan.to_param, :pendidikan => valid_attributes}, valid_session
        response.should redirect_to(pendidikan)
      end
    end

    describe "with invalid params" do
      it "assigns the pendidikan as @pendidikan" do
        pendidikan = Pendidikan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pendidikan.any_instance.stub(:save).and_return(false)
        put :update, {:id => pendidikan.to_param, :pendidikan => { "from" => "invalid value" }}, valid_session
        assigns(:pendidikan).should eq(pendidikan)
      end

      it "re-renders the 'edit' template" do
        pendidikan = Pendidikan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pendidikan.any_instance.stub(:save).and_return(false)
        put :update, {:id => pendidikan.to_param, :pendidikan => { "from" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pendidikan" do
      pendidikan = Pendidikan.create! valid_attributes
      expect {
        delete :destroy, {:id => pendidikan.to_param}, valid_session
      }.to change(Pendidikan, :count).by(-1)
    end

    it "redirects to the pendidikans list" do
      pendidikan = Pendidikan.create! valid_attributes
      delete :destroy, {:id => pendidikan.to_param}, valid_session
      response.should redirect_to(pendidikans_url)
    end
  end

end
