require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PengalamenController do

  # This should return the minimal set of attributes required to create a valid
  # Pengalaman. As you add validations to Pengalaman, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "campany" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PengalamenController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all pengalamen as @pengalamen" do
      pengalaman = Pengalaman.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pengalamen).should eq([pengalaman])
    end
  end

  describe "GET show" do
    it "assigns the requested pengalaman as @pengalaman" do
      pengalaman = Pengalaman.create! valid_attributes
      get :show, {:id => pengalaman.to_param}, valid_session
      assigns(:pengalaman).should eq(pengalaman)
    end
  end

  describe "GET new" do
    it "assigns a new pengalaman as @pengalaman" do
      get :new, {}, valid_session
      assigns(:pengalaman).should be_a_new(Pengalaman)
    end
  end

  describe "GET edit" do
    it "assigns the requested pengalaman as @pengalaman" do
      pengalaman = Pengalaman.create! valid_attributes
      get :edit, {:id => pengalaman.to_param}, valid_session
      assigns(:pengalaman).should eq(pengalaman)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pengalaman" do
        expect {
          post :create, {:pengalaman => valid_attributes}, valid_session
        }.to change(Pengalaman, :count).by(1)
      end

      it "assigns a newly created pengalaman as @pengalaman" do
        post :create, {:pengalaman => valid_attributes}, valid_session
        assigns(:pengalaman).should be_a(Pengalaman)
        assigns(:pengalaman).should be_persisted
      end

      it "redirects to the created pengalaman" do
        post :create, {:pengalaman => valid_attributes}, valid_session
        response.should redirect_to(Pengalaman.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pengalaman as @pengalaman" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pengalaman.any_instance.stub(:save).and_return(false)
        post :create, {:pengalaman => { "campany" => "invalid value" }}, valid_session
        assigns(:pengalaman).should be_a_new(Pengalaman)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pengalaman.any_instance.stub(:save).and_return(false)
        post :create, {:pengalaman => { "campany" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pengalaman" do
        pengalaman = Pengalaman.create! valid_attributes
        # Assuming there are no other pengalamen in the database, this
        # specifies that the Pengalaman created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pengalaman.any_instance.should_receive(:update_attributes).with({ "campany" => "MyString" })
        put :update, {:id => pengalaman.to_param, :pengalaman => { "campany" => "MyString" }}, valid_session
      end

      it "assigns the requested pengalaman as @pengalaman" do
        pengalaman = Pengalaman.create! valid_attributes
        put :update, {:id => pengalaman.to_param, :pengalaman => valid_attributes}, valid_session
        assigns(:pengalaman).should eq(pengalaman)
      end

      it "redirects to the pengalaman" do
        pengalaman = Pengalaman.create! valid_attributes
        put :update, {:id => pengalaman.to_param, :pengalaman => valid_attributes}, valid_session
        response.should redirect_to(pengalaman)
      end
    end

    describe "with invalid params" do
      it "assigns the pengalaman as @pengalaman" do
        pengalaman = Pengalaman.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pengalaman.any_instance.stub(:save).and_return(false)
        put :update, {:id => pengalaman.to_param, :pengalaman => { "campany" => "invalid value" }}, valid_session
        assigns(:pengalaman).should eq(pengalaman)
      end

      it "re-renders the 'edit' template" do
        pengalaman = Pengalaman.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pengalaman.any_instance.stub(:save).and_return(false)
        put :update, {:id => pengalaman.to_param, :pengalaman => { "campany" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pengalaman" do
      pengalaman = Pengalaman.create! valid_attributes
      expect {
        delete :destroy, {:id => pengalaman.to_param}, valid_session
      }.to change(Pengalaman, :count).by(-1)
    end

    it "redirects to the pengalamen list" do
      pengalaman = Pengalaman.create! valid_attributes
      delete :destroy, {:id => pengalaman.to_param}, valid_session
      response.should redirect_to(pengalamen_url)
    end
  end

end
